import 'a_i_s_field_scope.dart';

enum AISField {
  drawing(
    fieldId: 'drawing',
    defaultName: 'Drawing',
    displayName: 'Drawing',
    scope: [AISFieldScope.general],
  ),
  sheet(
    fieldId: 'sheet',
    defaultName: 'Sheet #',
    displayName: 'Sheet #',
    scope: [AISFieldScope.general],
  ),
  ofSheet(
    fieldId: 'of_sheet',
    defaultName: 'of Sheet #',
    displayName: 'of Sheet #',
    scope: [AISFieldScope.general],
  ),
  lineNumber(
    fieldId: 'line_number',
    defaultName: 'Line Number',
    displayName: 'Line Number',
    scope: [AISFieldScope.general],
  ),
  pipeSpec(
    fieldId: 'pipe_spec',
    defaultName: 'Pipe Spec',
    displayName: 'Pipe Spec',
    scope: [AISFieldScope.general],
  ),
  insulationSpec(
    fieldId: 'insulation_spec',
    defaultName: 'Insulation Spec',
    displayName: 'Insulation Spec',
    scope: [AISFieldScope.general],
  ),
  pwht(
    fieldId: 'pwht',
    defaultName: 'PWHT',
    displayName: 'PWHT',
    scope: [AISFieldScope.general],
  ),
  pAndId(
    fieldId: 'p_and_id',
    defaultName: 'P&ID',
    displayName: 'P&ID',
    scope: [AISFieldScope.general],
  ),
  area(
    fieldId: 'area',
    defaultName: 'Area',
    displayName: 'Area',
    scope: [AISFieldScope.general],
  ),
  unit(
    fieldId: 'unit',
    defaultName: 'Unit',
    displayName: 'Unit',
    scope: [AISFieldScope.general],
  ),
  item(
    fieldId: 'item',
    defaultName: 'Item',
    displayName: 'Item',
    scope: [AISFieldScope.bom],
  ),
  tag(
    fieldId: 'tag',
    defaultName: 'Tag',
    displayName: 'Tag',
    scope: [AISFieldScope.bom],
  ),
  quantity(
    fieldId: 'quantity',
    defaultName: 'Quantity',
    displayName: 'Quantity',
    scope: [AISFieldScope.bom],
  ),
  npsOd(
    fieldId: 'nps_od',
    defaultName: 'NPS (OD)',
    displayName: 'NPS (OD)',
    scope: [AISFieldScope.general, AISFieldScope.bom, AISFieldScope.fab],
  ),
  npsId(
    fieldId: 'nps_id',
    defaultName: 'NPS (ID)',
    displayName: 'NPS (ID)',
    scope: [AISFieldScope.general, AISFieldScope.bom, AISFieldScope.fab],
  ),
  materialDescription(
    fieldId: 'material_description',
    defaultName: 'Material Description',
    displayName: 'Material Description',
    scope: [AISFieldScope.bom, AISFieldScope.spec],
  ),
  heatTrace(
    fieldId: 'heat_trace',
    defaultName: 'Heat Trace',
    displayName: 'Heat Trace',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  insulationThickness(
    fieldId: 'insulation_thickness',
    defaultName: 'Insulation Thickness',
    displayName: 'Insulation Thickness',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  clientDocumentId(
    fieldId: 'client_document_id',
    defaultName: 'Client Document ID',
    displayName: 'Client Document ID',
    scope: [AISFieldScope.general],
  ),
  coordinate(
    fieldId: 'coordinate',
    defaultName: 'Coordinate',
    displayName: 'Coordinate',
    scope: [AISFieldScope.general],
  ),
  cutPieceNo(
    fieldId: 'cut_piece_no',
    defaultName: 'Cut Piece No',
    displayName: 'Cut Piece No',
    scope: [AISFieldScope.fab],
  ),
  designCode(
    fieldId: 'design_code',
    defaultName: 'Design Code',
    displayName: 'Design Code',
    scope: [AISFieldScope.general],
  ),
  dp1(
    fieldId: 'dp1',
    defaultName: 'Design Pressure 1',
    displayName: 'Design Pressure 1',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  dp2(
    fieldId: 'dp2',
    defaultName: 'Design Pressure 2',
    displayName: 'Design Pressure 2',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  dt1(
    fieldId: 'dt1',
    defaultName: 'Design Temp. 1',
    displayName: 'Design Temp. 1',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  dt2(
    fieldId: 'dt2',
    defaultName: 'Design Temp. 2',
    displayName: 'Design Temp. 2',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  document(
    fieldId: 'document',
    defaultName: 'Document #',
    displayName: 'Document #',
    scope: [AISFieldScope.general],
  ),
  documentDescription(
    fieldId: 'document_description',
    defaultName: 'Document Description',
    displayName: 'Document Description',
    scope: [AISFieldScope.general],
  ),
  documentId(
    fieldId: 'document_id',
    defaultName: 'Document ID',
    displayName: 'Document ID',
    scope: [AISFieldScope.general],
  ),
  documentTitle(
    fieldId: 'document_title',
    defaultName: 'Document Title',
    displayName: 'Document Title',
    scope: [AISFieldScope.general],
  ),
  elevation(
    fieldId: 'elevation',
    defaultName: 'Elevation',
    displayName: 'Elevation',
    scope: [AISFieldScope.general],
  ),
  ident(
    fieldId: 'ident',
    defaultName: 'IDENT',
    displayName: 'IDENT',
    scope: [AISFieldScope.bom],
  ),
  length(
    fieldId: 'length',
    defaultName: 'Length',
    displayName: 'Length',
    scope: [AISFieldScope.fab],
  ),
  mediumCode(
    fieldId: 'medium_code',
    defaultName: 'Medium Code',
    displayName: 'Medium Code',
    scope: [AISFieldScope.general],
  ),
  op1(
    fieldId: 'op1',
    defaultName: 'Operating Pressure 1',
    displayName: 'Operating Pressure 1',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  op2(
    fieldId: 'op2',
    defaultName: 'Operating Pressure 2',
    displayName: 'Operating Pressure 2',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  opt1(
    fieldId: 'opt1',
    defaultName: 'Operating Temp. 1',
    displayName: 'Operating Temp. 1',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  opt2(
    fieldId: 'opt2',
    defaultName: 'Operating Temp. 2',
    displayName: 'Operating Temp. 2',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  paintSpec(
    fieldId: 'paint_spec',
    defaultName: 'Paint Spec',
    displayName: 'Paint Spec',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  pipeStandard(
    fieldId: 'pipe_standard',
    defaultName: 'Pipe Standard',
    displayName: 'Pipe Standard',
    scope: [AISFieldScope.general],
  ),
  pos(
    fieldId: 'pos',
    defaultName: 'POS',
    displayName: 'POS',
    scope: [AISFieldScope.bom],
  ),
  processLineList(
    fieldId: 'process_line_list',
    defaultName: 'Process Line List',
    displayName: 'Process Line List',
    scope: [AISFieldScope.general],
  ),
  processUnit(
    fieldId: 'process_unit',
    defaultName: 'Process Unit',
    displayName: 'Process Unit',
    scope: [AISFieldScope.general],
  ),
  projectId(
    fieldId: 'project_id',
    defaultName: 'Project ID',
    displayName: 'Project ID',
    scope: [AISFieldScope.general],
  ),
  projectName(
    fieldId: 'project_name',
    defaultName: 'Project Name',
    displayName: 'Project Name',
    scope: [AISFieldScope.general],
  ),
  revision(
    fieldId: 'revision',
    defaultName: 'Revision',
    displayName: 'Revision',
    scope: [AISFieldScope.general],
  ),
  sequence(
    fieldId: 'sequence',
    defaultName: 'Sequence #',
    displayName: 'Sequence #',
    scope: [AISFieldScope.general],
  ),
  service(
    fieldId: 'service',
    defaultName: 'Service',
    displayName: 'Service',
    scope: [AISFieldScope.general],
  ),
  spoolNumber(
    fieldId: 'spool_number',
    defaultName: 'Spool Number',
    displayName: 'Spool Number',
    scope: [AISFieldScope.general],
  ),
  system(
    fieldId: 'system',
    defaultName: 'System',
    displayName: 'System',
    scope: [AISFieldScope.general],
  ),
  vendorDocumentId(
    fieldId: 'vendor_document_id',
    defaultName: 'Vendor Document ID',
    displayName: 'Vendor Document ID',
    scope: [AISFieldScope.general],
  ),
  weldId(
    fieldId: 'weld_id',
    defaultName: 'Weld ID',
    displayName: 'Weld ID',
    scope: [AISFieldScope.general],
  ),
  xray(
    fieldId: 'xray',
    defaultName: 'X-Ray',
    displayName: 'X-Ray',
    scope: [AISFieldScope.general, AISFieldScope.spec],
  ),
  sysBuild(
    fieldId: 'sys_build',
    defaultName: 'Sys Build',
    displayName: 'Sys Build',
    scope: [],
  ),
  sysFilename(
    fieldId: 'sys_filename',
    defaultName: 'Sys Filename',
    displayName: 'Sys Filename',
    scope: [],
  ),
  sysPath(
    fieldId: 'sys_path',
    defaultName: 'Sys Path',
    displayName: 'Sys Path',
    scope: [],
  ),
  bom(
    fieldId: 'bom',
    defaultName: 'BOM',
    displayName: 'BOM',
    scope: [AISFieldScope.general],
  ),
  spec(
    fieldId: 'spec',
    defaultName: 'Spec',
    displayName: 'Spec',
    scope: [AISFieldScope.general],
  ),
  fab(
    fieldId: 'fab',
    defaultName: 'Fab',
    displayName: 'Fab',
    scope: [AISFieldScope.general],
  ),
  ;

  const AISField({
    required this.fieldId,
    required this.defaultName,
    required this.displayName,
    required this.scope,
  });

  final String fieldId;
  final String defaultName;
  final String displayName;
  final List<AISFieldScope> scope;

  static AISField fromString(String value) {
    return switch (value) {
      'drawing' => AISField.drawing,
      'sheet' => AISField.sheet,
      'of_sheet' => AISField.ofSheet,
      'line_number' => AISField.lineNumber,
      'pipe_spec' => AISField.pipeSpec,
      'insulation_spec' => AISField.insulationSpec,
      'pwht' => AISField.pwht,
      'p_and_id' => AISField.pAndId,
      'area' => AISField.area,
      'unit' => AISField.unit,
      'item' => AISField.item,
      'tag' => AISField.tag,
      'quantity' => AISField.quantity,
      'nps_od' => AISField.npsOd,
      'nps_id' => AISField.npsId,
      'material_description' => AISField.materialDescription,
      'heat_trace' => AISField.heatTrace,
      'insulation_thickness' => AISField.insulationThickness,
      'client_document_id' => AISField.clientDocumentId,
      'coordinate' => AISField.coordinate,
      'cut_piece_no' => AISField.cutPieceNo,
      'design_code' => AISField.designCode,
      'dp1' => AISField.dp1,
      'dp2' => AISField.dp2,
      'dt1' => AISField.dt1,
      'dt2' => AISField.dt2,
      'document' => AISField.document,
      'document_description' => AISField.documentDescription,
      'document_id' => AISField.documentId,
      'document_title' => AISField.documentTitle,
      'elevation' => AISField.elevation,
      'ident' => AISField.ident,
      'length' => AISField.length,
      'medium_code' => AISField.mediumCode,
      'op1' => AISField.op1,
      'op2' => AISField.op2,
      'opt1' => AISField.opt1,
      'opt2' => AISField.opt2,
      'paint_spec' => AISField.paintSpec,
      'pipe_standard' => AISField.pipeStandard,
      'pos' => AISField.pos,
      'process_line_list' => AISField.processLineList,
      'process_unit' => AISField.processUnit,
      'project_id' => AISField.projectId,
      'project_name' => AISField.projectName,
      'revision' => AISField.revision,
      'sequence' => AISField.sequence,
      'service' => AISField.service,
      'spool_number' => AISField.spoolNumber,
      'system' => AISField.system,
      'vendor_document_id' => AISField.vendorDocumentId,
      'weld_id' => AISField.weldId,
      'xray' => AISField.xray,
      'sys_build' => AISField.sysBuild,
      'sys_filename' => AISField.sysFilename,
      'sys_path' => AISField.sysPath,
      'bom' => AISField.bom,
      'spec' => AISField.spec,
      'fab' => AISField.fab,
      _ => AISField.drawing,
    };
  }
}
