import 'mto_column_scope.dart';

enum MtoColumns {
  drawing(
    fieldId: 'drawing',
    defaultName: 'Drawing',
    displayName: 'Drawing',
    scope: [MtoFieldScope.general],
  ),
  sheet(
    fieldId: 'sheet',
    defaultName: 'Sheet #',
    displayName: 'Sheet #',
    scope: [MtoFieldScope.general],
  ),
  ofSheet(
    fieldId: 'of_sheet',
    defaultName: 'of Sheet #',
    displayName: 'of Sheet #',
    scope: [MtoFieldScope.general],
  ),
  lineNumber(
    fieldId: 'line_number',
    defaultName: 'Line Number',
    displayName: 'Line Number',
    scope: [MtoFieldScope.general],
  ),
  pipeSpec(
    fieldId: 'pipe_spec',
    defaultName: 'Pipe Spec',
    displayName: 'Pipe Spec',
    scope: [MtoFieldScope.general],
  ),
  insulationSpec(
    fieldId: 'insulation_spec',
    defaultName: 'Insulation Spec',
    displayName: 'Insulation Spec',
    scope: [MtoFieldScope.general],
  ),
  pwht(
    fieldId: 'pwht',
    defaultName: 'PWHT',
    displayName: 'PWHT',
    scope: [MtoFieldScope.general],
  ),
  pAndId(
    fieldId: 'p_and_id',
    defaultName: 'P&ID',
    displayName: 'P&ID',
    scope: [MtoFieldScope.general],
  ),
  area(
    fieldId: 'area',
    defaultName: 'Area',
    displayName: 'Area',
    scope: [MtoFieldScope.general],
  ),
  unit(
    fieldId: 'unit',
    defaultName: 'Unit',
    displayName: 'Unit',
    scope: [MtoFieldScope.general, MtoFieldScope.piping],
  ),
  item(
    fieldId: 'item',
    defaultName: 'Item',
    displayName: 'Item',
    scope: [MtoFieldScope.bom],
  ),
  tag(
    fieldId: 'tag',
    defaultName: 'Tag',
    displayName: 'Tag',
    scope: [MtoFieldScope.bom],
  ),
  quantity(
    fieldId: 'quantity',
    defaultName: 'Quantity',
    displayName: 'Quantity',
    scope: [MtoFieldScope.bom],
  ),
  npsOd(
    fieldId: 'nps_od',
    defaultName: 'NPS (OD)',
    displayName: 'NPS (OD)',
    scope: [MtoFieldScope.general, MtoFieldScope.bom, MtoFieldScope.fab],
  ),
  npsId(
    fieldId: 'nps_id',
    defaultName: 'NPS (ID)',
    displayName: 'NPS (ID)',
    scope: [MtoFieldScope.general, MtoFieldScope.bom, MtoFieldScope.fab],
  ),
  materialDescription(
    fieldId: 'material_description',
    defaultName: 'Material Description',
    displayName: 'Material Description',
    scope: [MtoFieldScope.bom, MtoFieldScope.spec],
  ),
  heatTrace(
    fieldId: 'heat_trace',
    defaultName: 'Heat Trace',
    displayName: 'Heat Trace',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  insulationThickness(
    fieldId: 'insulation_thickness',
    defaultName: 'Insulation Thickness',
    displayName: 'Insulation Thickness',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  clientDocumentId(
    fieldId: 'client_document_id',
    defaultName: 'Client Document ID',
    displayName: 'Client Document ID',
    scope: [MtoFieldScope.general],
  ),
  coordinate(
    fieldId: 'coordinate',
    defaultName: 'Coordinate',
    displayName: 'Coordinate',
    scope: [MtoFieldScope.general],
  ),
  cutPieceNo(
    fieldId: 'cut_piece_no',
    defaultName: 'Cut Piece No',
    displayName: 'Cut Piece No',
    scope: [MtoFieldScope.fab],
  ),
  designCode(
    fieldId: 'design_code',
    defaultName: 'Design Code',
    displayName: 'Design Code',
    scope: [MtoFieldScope.general],
  ),
  dp1(
    fieldId: 'dp1',
    defaultName: 'Design Pressure 1',
    displayName: 'Design Pressure 1',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  dp2(
    fieldId: 'dp2',
    defaultName: 'Design Pressure 2',
    displayName: 'Design Pressure 2',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  dt1(
    fieldId: 'dt1',
    defaultName: 'Design Temp. 1',
    displayName: 'Design Temp. 1',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  dt2(
    fieldId: 'dt2',
    defaultName: 'Design Temp. 2',
    displayName: 'Design Temp. 2',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  document(
    fieldId: 'document',
    defaultName: 'Document #',
    displayName: 'Document #',
    scope: [MtoFieldScope.general],
  ),
  documentDescription(
    fieldId: 'document_description',
    defaultName: 'Document Description',
    displayName: 'Document Description',
    scope: [MtoFieldScope.general],
  ),
  documentId(
    fieldId: 'document_id',
    defaultName: 'Document ID',
    displayName: 'Document ID',
    scope: [MtoFieldScope.general],
  ),
  documentTitle(
    fieldId: 'document_title',
    defaultName: 'Document Title',
    displayName: 'Document Title',
    scope: [MtoFieldScope.general],
  ),
  elevation(
    fieldId: 'elevation',
    defaultName: 'Elevation',
    displayName: 'Elevation',
    scope: [MtoFieldScope.general],
  ),
  ident(
    fieldId: 'ident',
    defaultName: 'IDENT',
    displayName: 'IDENT',
    scope: [MtoFieldScope.bom],
  ),
  length(
    fieldId: 'length',
    defaultName: 'Length',
    displayName: 'Length',
    scope: [MtoFieldScope.fab],
  ),
  mediumCode(
    fieldId: 'medium_code',
    defaultName: 'Medium Code',
    displayName: 'Medium Code',
    scope: [MtoFieldScope.general],
  ),
  op1(
    fieldId: 'op1',
    defaultName: 'Operating Pressure 1',
    displayName: 'Operating Pressure 1',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  op2(
    fieldId: 'op2',
    defaultName: 'Operating Pressure 2',
    displayName: 'Operating Pressure 2',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  opt1(
    fieldId: 'opt1',
    defaultName: 'Operating Temp. 1',
    displayName: 'Operating Temp. 1',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  opt2(
    fieldId: 'opt2',
    defaultName: 'Operating Temp. 2',
    displayName: 'Operating Temp. 2',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  paintSpec(
    fieldId: 'paint_spec',
    defaultName: 'Paint Spec',
    displayName: 'Paint Spec',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  pipeStandard(
    fieldId: 'pipe_standard',
    defaultName: 'Pipe Standard',
    displayName: 'Pipe Standard',
    scope: [MtoFieldScope.general],
  ),
  pos(
    fieldId: 'pos',
    defaultName: 'POS',
    displayName: 'POS',
    scope: [MtoFieldScope.bom],
  ),
  processLineList(
    fieldId: 'process_line_list',
    defaultName: 'Process Line List',
    displayName: 'Process Line List',
    scope: [MtoFieldScope.general],
  ),
  processUnit(
    fieldId: 'process_unit',
    defaultName: 'Process Unit',
    displayName: 'Process Unit',
    scope: [MtoFieldScope.general],
  ),
  projectId(
    fieldId: 'project_id',
    defaultName: 'Project ID',
    displayName: 'Project ID',
    scope: [MtoFieldScope.general],
  ),
  projectName(
    fieldId: 'project_name',
    defaultName: 'Project Name',
    displayName: 'Project Name',
    scope: [MtoFieldScope.general],
  ),
  revision(
    fieldId: 'revision',
    defaultName: 'Revision',
    displayName: 'Revision',
    scope: [MtoFieldScope.general],
  ),
  sequence(
    fieldId: 'sequence',
    defaultName: 'Sequence #',
    displayName: 'Sequence #',
    scope: [MtoFieldScope.general],
  ),
  service(
    fieldId: 'service',
    defaultName: 'Service',
    displayName: 'Service',
    scope: [MtoFieldScope.general],
  ),
  spoolNumber(
    fieldId: 'spool_number',
    defaultName: 'Spool Number',
    displayName: 'Spool Number',
    scope: [MtoFieldScope.general],
  ),
  system(
    fieldId: 'system',
    defaultName: 'System',
    displayName: 'System',
    scope: [MtoFieldScope.general],
  ),
  vendorDocumentId(
    fieldId: 'vendor_document_id',
    defaultName: 'Vendor Document ID',
    displayName: 'Vendor Document ID',
    scope: [MtoFieldScope.general],
  ),
  weldId(
    fieldId: 'weld_id',
    defaultName: 'Weld ID',
    displayName: 'Weld ID',
    scope: [MtoFieldScope.general],
  ),
  xray(
    fieldId: 'xray',
    defaultName: 'X-Ray',
    displayName: 'X-Ray',
    scope: [MtoFieldScope.general, MtoFieldScope.spec],
  ),
  sysBuild(
    fieldId: 'sys_build',
    defaultName: 'Sys Build',
    displayName: 'Sys Build',
    scope: [],
  ),
  sysFilename(
    fieldId: 'sys_filename',
    defaultName: 'Sys Filename',
    displayName: 'Sys Filename',
    scope: [],
  ),
  sysPath(
    fieldId: 'sys_path',
    defaultName: 'Sys Path',
    displayName: 'Sys Path',
    scope: [],
  ),
  generalCategory(
    fieldId: 'general_category',
    defaultName: 'generalCategory',
    displayName: 'General Category',
    scope: [MtoFieldScope.piping],
  ),
  rfqScope(
    fieldId: 'rfq_scope',
    defaultName: 'rfqScope',
    displayName: 'RFQ Scope',
    scope: [MtoFieldScope.piping],
  ),
  size1(
    fieldId: 'size_1',
    defaultName: 'size1',
    displayName: 'Size 1',
    scope: [MtoFieldScope.piping],
  ),
  size2(
    fieldId: 'size_2',
    defaultName: 'size2',
    displayName: 'Size 2',
    scope: [MtoFieldScope.piping],
  ),
  schedule(
    fieldId: 'schedule',
    defaultName: 'schedule',
    displayName: 'Schedule',
    scope: [MtoFieldScope.piping],
  ),
  rating(
    fieldId: 'rating',
    defaultName: 'rating',
    displayName: 'Rating',
    scope: [MtoFieldScope.piping],
  ),
  astm(
    fieldId: 'astm',
    defaultName: 'astm',
    displayName: 'ASTM',
    scope: [MtoFieldScope.piping],
  ),
  grade(
    fieldId: 'grade',
    defaultName: 'grade',
    displayName: 'Grade',
    scope: [MtoFieldScope.piping],
  ),
  asmeAnsi(
    fieldId: 'asme_ansi',
    defaultName: 'asmeAnsi',
    displayName: 'ASME ANSI',
    scope: [MtoFieldScope.piping],
  ),
  material(
    fieldId: 'material',
    defaultName: 'material',
    displayName: 'Material',
    scope: [MtoFieldScope.piping],
  ),
  coating(
    fieldId: 'coating',
    defaultName: 'coating',
    displayName: 'Coating',
    scope: [MtoFieldScope.piping],
  ),
  forging(
    fieldId: 'forging',
    defaultName: 'forging',
    displayName: 'Forging',
    scope: [MtoFieldScope.piping],
  ),
  ends(
    fieldId: 'ends',
    defaultName: 'ends',
    displayName: 'Ends',
    scope: [MtoFieldScope.piping],
  ),
  weldType(
    fieldId: 'weld_type',
    defaultName: 'weldType',
    displayName: 'Weld Type',
    scope: [MtoFieldScope.piping],
  ),
  additionalInformation(
    fieldId: 'additional_information',
    defaultName: 'additionalInformation',
    displayName: 'Additional Information',
    scope: [MtoFieldScope.piping],
  ),
  excludeFromRfq(
    fieldId: 'exclude_from_rfq',
    defaultName: 'excludeFromRfq',
    displayName: 'Exclude From RFQ',
    scope: [MtoFieldScope.piping],
  ),
  takeoffNotes(
    fieldId: 'takeoff_notes',
    defaultName: 'takeoffNotes',
    displayName: 'Takeoff Notes',
    scope: [MtoFieldScope.piping],
  ),
  maxElevation(
    fieldId: 'max_elevation',
    defaultName: 'Max Elevation',
    displayName: 'Max Elevation',
    scope: [MtoFieldScope.general],
  ),
  minElevation(
    fieldId: 'min_elevation',
    defaultName: 'Min Elevation',
    displayName: 'Min Elevation',
    scope: [MtoFieldScope.general],
  ),
  averageElevation(
    fieldId: 'average_elevation',
    defaultName: 'Average Elevation',
    displayName: 'Average Elevation',
    scope: [MtoFieldScope.general],
  ),
  ;

  const MtoColumns({
    required this.fieldId,
    required this.defaultName,
    required this.displayName,
    required this.scope,
  });

  final String fieldId;
  final String defaultName;
  final String displayName;
  final List<MtoFieldScope> scope;

  static MtoColumns fromString(String value) {
    return switch (value) {
      'drawing' => MtoColumns.drawing,
      'sheet' => MtoColumns.sheet,
      'of_sheet' => MtoColumns.ofSheet,
      'line_number' => MtoColumns.lineNumber,
      'pipe_spec' => MtoColumns.pipeSpec,
      'insulation_spec' => MtoColumns.insulationSpec,
      'pwht' => MtoColumns.pwht,
      'p_and_id' => MtoColumns.pAndId,
      'area' => MtoColumns.area,
      'unit' => MtoColumns.unit,
      'item' => MtoColumns.item,
      'tag' => MtoColumns.tag,
      'quantity' => MtoColumns.quantity,
      'nps_od' => MtoColumns.npsOd,
      'nps_id' => MtoColumns.npsId,
      'material_description' => MtoColumns.materialDescription,
      'heat_trace' => MtoColumns.heatTrace,
      'insulation_thickness' => MtoColumns.insulationThickness,
      'client_document_id' => MtoColumns.clientDocumentId,
      'coordinate' => MtoColumns.coordinate,
      'cut_piece_no' => MtoColumns.cutPieceNo,
      'design_code' => MtoColumns.designCode,
      'dp1' => MtoColumns.dp1,
      'dp2' => MtoColumns.dp2,
      'dt1' => MtoColumns.dt1,
      'dt2' => MtoColumns.dt2,
      'document' => MtoColumns.document,
      'document_description' => MtoColumns.documentDescription,
      'document_id' => MtoColumns.documentId,
      'document_title' => MtoColumns.documentTitle,
      'elevation' => MtoColumns.elevation,
      'ident' => MtoColumns.ident,
      'length' => MtoColumns.length,
      'medium_code' => MtoColumns.mediumCode,
      'op1' => MtoColumns.op1,
      'op2' => MtoColumns.op2,
      'opt1' => MtoColumns.opt1,
      'opt2' => MtoColumns.opt2,
      'paint_spec' => MtoColumns.paintSpec,
      'pipe_standard' => MtoColumns.pipeStandard,
      'pos' => MtoColumns.pos,
      'process_line_list' => MtoColumns.processLineList,
      'process_unit' => MtoColumns.processUnit,
      'project_id' => MtoColumns.projectId,
      'project_name' => MtoColumns.projectName,
      'revision' => MtoColumns.revision,
      'sequence' => MtoColumns.sequence,
      'service' => MtoColumns.service,
      'spool_number' => MtoColumns.spoolNumber,
      'system' => MtoColumns.system,
      'vendor_document_id' => MtoColumns.vendorDocumentId,
      'weld_id' => MtoColumns.weldId,
      'xray' => MtoColumns.xray,
      'sys_build' => MtoColumns.sysBuild,
      'sys_filename' => MtoColumns.sysFilename,
      'sys_path' => MtoColumns.sysPath,
      'general_category' => MtoColumns.generalCategory,
      'rfq_scope' => MtoColumns.rfqScope,
      'size_1' => MtoColumns.size1,
      'size_2' => MtoColumns.size2,
      'schedule' => MtoColumns.schedule,
      'rating' => MtoColumns.rating,
      'astm' => MtoColumns.astm,
      'grade' => MtoColumns.grade,
      'asme_ansi' => MtoColumns.asmeAnsi,
      'material' => MtoColumns.material,
      'coating' => MtoColumns.coating,
      'forging' => MtoColumns.forging,
      'ends' => MtoColumns.ends,
      'weld_type' => MtoColumns.weldType,
      'additional_information' => MtoColumns.additionalInformation,
      'exclude_from_rfq' => MtoColumns.excludeFromRfq,
      'takeoff_notes' => MtoColumns.takeoffNotes,
      'max_elevation' => MtoColumns.maxElevation,
      'min_elevation' => MtoColumns.minElevation,
      'average_elevation' => MtoColumns.averageElevation,
      _ => MtoColumns.drawing,
    };
  }
}
